name: Build Docker Image

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code from your repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Build the Docker image
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag waymo:v1.0
